# Generated by Django 5.2.8 on 2025-12-09 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_inventario', models.CharField(max_length=50, unique=True)),
                ('tipo_equipo', models.CharField(choices=[('computadora', 'Computadora'), ('laptop', 'Laptop'), ('servidor', 'Servidor'), ('router', 'Router'), ('switch', 'Switch'), ('impresora', 'Impresora'), ('proyector', 'Proyector'), ('tablet', 'Tablet'), ('otros', 'Otros')], max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('numero_serie', models.CharField(max_length=100, unique=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'En Mantenimiento'), ('baja', 'Dado de Baja')], default='activo', max_length=20)),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha_adquisicion', models.DateField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('especificaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_mantenimiento', models.DateField()),
                ('tipo_mantenimiento', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('diagnostico', 'Diagnóstico')], max_length=20)),
                ('descripcion', models.TextField()),
                ('tecnico', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], max_length=20)),
                ('fecha_proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario_equipos.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='Red',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_red', models.CharField(max_length=100)),
                ('tipo_red', models.CharField(choices=[('lan', 'LAN'), ('wlan', 'WLAN'), ('wan', 'WAN')], max_length=10)),
                ('direccion_ip', models.GenericIPAddressField()),
                ('mascara_subred', models.GenericIPAddressField()),
                ('gateway', models.GenericIPAddressField()),
                ('dns', models.GenericIPAddressField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('mantenimiento', 'En Mantenimiento')], default='activa', max_length=20)),
                ('ubicacion', models.CharField(max_length=100)),
                ('equipos_conectados', models.ManyToManyField(blank=True, to='inventario_equipos.equipo')),
            ],
        ),
    ]
