# Generated by Django 5.2.8 on 2026-01-20 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsable del Equipo'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='codigo_inventario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='especificaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fecha_adquisicion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.CharField(choices=[('computadora', 'Computadora'), ('laptop', 'Laptop'), ('servidor', 'Servidor'), ('router', 'Router'), ('switch', 'Switch'), ('impresora', 'Impresora'), ('proyector', 'Proyector'), ('tablet', 'Tablet'), ('otros', 'Otros')], default='computadora', max_length=20),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='red',
            name='direccion_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='red',
            name='dns',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='red',
            name='gateway',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='red',
            name='mascara_subred',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='red',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
