# Generated by Django 5.2.8 on 2026-01-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_equipos', '0002_equipo_responsable_alter_equipo_codigo_inventario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mantenimiento',
            name='costo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
