# Generated by Django 5.2.8 on 2026-01-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_calificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='nombre_actividad',
            field=models.CharField(blank=True, help_text='Ej: Lección pág. 40', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='periodo_academico',
            field=models.CharField(choices=[('T1', 'Trimestre 1'), ('T2', 'Trimestre 2'), ('T3', 'Trimestre 3')], default='T1', max_length=20),
        ),
    ]
