# Generated by Django 5.2.8 on 2026-01-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_calificaciones', '0002_calificacion_nombre_actividad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'ordering': ['numero_lista', 'estudiante__usuario__last_name'], 'verbose_name': 'Matrícula', 'verbose_name_plural': 'Matrículas'},
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('estudiante', 'curso')},
        ),
        migrations.AddField(
            model_name='matricula',
            name='numero_lista',
            field=models.PositiveIntegerField(blank=True, help_text='Ej: 1, 2, 3... (Se puede repetir en distintos cursos)', null=True, verbose_name='N° de Lista'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('curso', 'numero_lista'), ('estudiante', 'curso')},
        ),
    ]
