# Generated by Django 5.2.8 on 2026-01-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registro_calificaciones', '0003_alter_matricula_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='codigo_estudiante',
        ),
    ]
