# Generated by Django 5.2.8 on 2026-01-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_calificaciones', '0004_remove_estudiante_codigo_estudiante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='tipo_evaluacion',
            field=models.CharField(choices=[('actividad', 'Actividad/Tarea (70%)'), ('proyecto', 'Proyecto Final (30%)'), ('examen', 'Examen (30%)')], max_length=50),
        ),
    ]
