# Generated by Django 5.2.8 on 2026-01-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_calificaciones', '0005_alter_calificacion_tipo_evaluacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='tipo_evaluacion',
            field=models.CharField(choices=[('actividad', 'Actividad/Tarea (70%)'), ('proyecto', 'Proyecto Final (10%)'), ('examen', 'Examen (20%)')], max_length=50),
        ),
    ]
