# Generated by Django 5.2.8 on 2026-01-27 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EncuestaAccesibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('nombre_encuestado', models.CharField(max_length=100, verbose_name='Nombre del Participante')),
                ('interfaz_facilita', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('parcialmente', 'Parcialmente'), ('tal_vez', 'Tal vez'), ('desconozco', 'Desconozco')], max_length=20, verbose_name='1. ¿La interfaz facilita localizar herramientas?')),
                ('afectacion_capacitacion', models.CharField(choices=[('obstaculo', 'Ha sido un obstáculo total'), ('dificultad', 'Me ha dificultado algunas cosas'), ('perdido', 'A veces me siento perdido'), ('sin_problemas', 'He podido manejarlo sin problemas')], max_length=20, verbose_name='2. ¿Cómo afecta la falta de capacitación?')),
                ('compatibilidad_equipos', models.CharField(choices=[('si', 'Sí'), ('lento', 'A veces falla o es lento'), ('inestable', 'Funciona de forma inestable'), ('no_soporta', 'Mi equipo no soporta la plataforma')], max_length=20, verbose_name='3. Nivel de compatibilidad de dispositivos')),
                ('identifica_soporte', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('parcialmente', 'Parcialmente'), ('tal_vez', 'Tal vez'), ('desconozco', 'Desconozco')], max_length=20, verbose_name='4. ¿Identifica canales de soporte técnico?')),
                ('desplazamiento_autonomo', models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'A veces'), ('rara_vez', 'Rara vez'), ('nunca', 'Nunca')], max_length=20, verbose_name='5. ¿Instalaciones permiten desplazamiento autónomo?')),
                ('elementos_apoyo', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('parcialmente', 'Parcialmente'), ('tal_vez', 'Tal vez'), ('desconozco', 'Desconozco')], max_length=20, verbose_name='6. ¿Cuenta con rampas, ascensores, señalética?')),
                ('recursos_accesibles', models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'A veces'), ('rara_vez', 'Rara vez'), ('nunca', 'Nunca')], max_length=20, verbose_name='7. ¿Laboratorios/Plataformas son accesibles?')),
                ('docentes_inclusivos', models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'A veces'), ('rara_vez', 'Rara vez'), ('nunca', 'Nunca')], max_length=20, verbose_name='8. ¿Docentes aplican metodologías inclusivas?')),
                ('contenidos_adaptados', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('parcialmente', 'Parcialmente'), ('tal_vez', 'Tal vez'), ('desconozco', 'Desconozco')], max_length=20, verbose_name='9. ¿Contenidos toman en cuenta necesidades educativas?')),
                ('materiales_accesibles', models.CharField(choices=[('siempre', 'Siempre'), ('casi_siempre', 'Casi siempre'), ('a_veces', 'A veces'), ('rara_vez', 'Rara vez'), ('nunca', 'Nunca')], max_length=20, verbose_name='10. ¿Se utilizan materiales adaptados?')),
                ('barrera_frecuente', models.CharField(choices=[('metodologias', 'Metodologías homogéneas'), ('recursos', 'Falta de recursos didácticos accesibles'), ('evaluaciones', 'Evaluaciones no adaptadas')], max_length=20, verbose_name='11. ¿Qué barrera identifica con mayor frecuencia?')),
                ('politicas_claras', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('parcialmente', 'Parcialmente'), ('tal_vez', 'Tal vez'), ('desconozco', 'Desconozco')], max_length=20, verbose_name='12. ¿Políticas claras sobre inclusión?')),
                ('capacitacion_docente', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('poca', 'Muy poca')], max_length=20, verbose_name='13. ¿Proceso de capacitación a docentes?')),
                ('conocimiento_bap', models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('parcialmente', 'Parcialmente'), ('tal_vez', 'Tal vez'), ('desconozco', 'Desconozco')], max_length=20, verbose_name='14. ¿Conocimiento sobre Barreras de Aprendizaje (BAP)?')),
            ],
        ),
    ]
