# Generated by Django 5.2.8 on 2026-01-30 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesibilidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encuestaaccesibilidad',
            name='afectacion_capacitacion',
        ),
        migrations.RemoveField(
            model_name='encuestaaccesibilidad',
            name='barrera_frecuente',
        ),
        migrations.RemoveField(
            model_name='encuestaaccesibilidad',
            name='capacitacion_docente',
        ),
        migrations.RemoveField(
            model_name='encuestaaccesibilidad',
            name='compatibilidad_equipos',
        ),
        migrations.RemoveField(
            model_name='encuestaaccesibilidad',
            name='conocimiento_bap',
        ),
        migrations.RemoveField(
            model_name='encuestaaccesibilidad',
            name='contenidos_adaptados',
        ),
        migrations.RemoveField(
            model_name='encuestaaccesibilidad',
            name='desplazamiento_autonomo',
        ),
        migrations.RemoveField(
            model_name='encuestaaccesibilidad',
            name='docentes_inclusivos',
        ),
        migrations.RemoveField(
            model_name='encuestaaccesibilidad',
            name='elementos_apoyo',
        ),
        migrations.RemoveField(
            model_name='encuestaaccesibilidad',
            name='identifica_soporte',
        ),
        migrations.RemoveField(
            model_name='encuestaaccesibilidad',
            name='interfaz_facilita',
        ),
        migrations.RemoveField(
            model_name='encuestaaccesibilidad',
            name='materiales_accesibles',
        ),
        migrations.RemoveField(
            model_name='encuestaaccesibilidad',
            name='politicas_claras',
        ),
        migrations.RemoveField(
            model_name='encuestaaccesibilidad',
            name='recursos_accesibles',
        ),
        migrations.AddField(
            model_name='encuestaaccesibilidad',
            name='q10_adaptaciones',
            field=models.CharField(choices=[('Siempre', 'Siempre'), ('A veces', 'A veces'), ('Nunca', 'Nunca')], default='-', max_length=20, verbose_name='10. ¿Se utilizan adaptaciones curriculares?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuestaaccesibilidad',
            name='q11_barreras',
            field=models.CharField(choices=[('Metodologias', 'Metodologías homogéneas'), ('Recursos', 'Falta de recursos didácticos accesibles'), ('Evaluaciones', 'Evaluaciones no adaptadas')], default='-', max_length=20, verbose_name='11. Barreras pedagógicas más frecuentes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuestaaccesibilidad',
            name='q12_politicas',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No'), ('Desconozco', 'Desconozco')], default='-', max_length=20, verbose_name='12. ¿Políticas claras sobre inclusión?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuestaaccesibilidad',
            name='q13_capacitacion_inst',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No'), ('Muy poca', 'Muy poca')], default='-', max_length=20, verbose_name='13. ¿Capacitación institucional a docentes?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuestaaccesibilidad',
            name='q14_conocimiento_bap',
            field=models.CharField(choices=[('Si', 'Si'), ('Parcialmente', 'Parcialmente'), ('Tal vez', 'Tal vez'), ('No', 'No')], default='-', max_length=20, verbose_name='14. ¿Conocimiento sobre Barreras BAP?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuestaaccesibilidad',
            name='q1_interfaz',
            field=models.CharField(choices=[('Si', 'Si'), ('Parcialmente', 'Parcialmente'), ('Tal vez', 'Tal vez'), ('No', 'No')], default='-', max_length=20, verbose_name='1. ¿La interfaz facilita la localización de herramientas?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuestaaccesibilidad',
            name='q2_capacitacion',
            field=models.CharField(choices=[('Obstaculo', 'Ha sido un obstáculo total'), ('Dificultad', 'Me ha dificultado algunas cosas'), ('Perdido', 'A veces me siento perdido'), ('SinProblemas', 'He podido manejarlo sin problemas')], default='-', max_length=20, verbose_name='2. Ausencia de capacitación sobre uso de tecnología'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuestaaccesibilidad',
            name='q3_compatibilidad',
            field=models.CharField(choices=[('Si', 'Si'), ('Lento', 'A veces falla o es lento'), ('Inestable', 'Funciona de forma inestable'), ('NoSoporta', 'Mi equipo no soporta la plataforma')], default='-', max_length=20, verbose_name='3. Nivel de compatibilidad de dispositivos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuestaaccesibilidad',
            name='q4_soporte',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No'), ('Tal vez', 'Tal vez')], default='-', max_length=20, verbose_name='4. ¿Identifica canales de soporte técnico?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuestaaccesibilidad',
            name='q5_instalaciones',
            field=models.CharField(choices=[('Siempre', 'Siempre'), ('Casi siempre', 'Casi siempre'), ('A veces', 'A veces'), ('Nunca', 'Nunca')], default='-', max_length=20, verbose_name='5. ¿Instalaciones permiten desplazamiento autónomo?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuestaaccesibilidad',
            name='q6_apoyo',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No'), ('Parcialmente', 'Parcialmente')], default='-', max_length=20, verbose_name='6. Elementos de apoyo (rampas, ascensores, señalética)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuestaaccesibilidad',
            name='q7_recursos_tec',
            field=models.CharField(choices=[('Siempre', 'Siempre'), ('A veces', 'A veces'), ('Nunca', 'Nunca')], default='-', max_length=20, verbose_name='7. ¿Recursos tecnológicos son accesibles?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuestaaccesibilidad',
            name='q8_metodologias',
            field=models.CharField(choices=[('Siempre', 'Siempre'), ('A veces', 'A veces'), ('Rara vez', 'Rara vez'), ('Nunca', 'Nunca')], default='-', max_length=20, verbose_name='8. ¿Docentes aplican metodologías inclusivas?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='encuestaaccesibilidad',
            name='q9_materiales',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No'), ('Parcialmente', 'Parcialmente')], default='-', max_length=20, verbose_name='9. ¿Contenidos diseñados para diversas necesidades?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='encuestaaccesibilidad',
            name='nombre_encuestado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre (Opcional)'),
        ),
    ]
