# Generated by Django 5.2.8 on 2026-01-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesibilidad', '0002_remove_encuestaaccesibilidad_afectacion_capacitacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestaaccesibilidad',
            name='q1_interfaz',
            field=models.CharField(choices=[('Si', 'Si'), ('Parcialmente', 'Parcialmente'), ('Tal vez', 'Tal vez'), ('No', 'No')], max_length=20, verbose_name='1. ¿Considera que la interfaz (organización visual, menús y botones de la pantalla) de la plataforma educativa facilita la localización de las herramientas necesarias para sus actividades?'),
        ),
    ]
