# Generated by Django 5.2.8 on 2026-01-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accesibilidad', '0003_alter_encuestaaccesibilidad_q1_interfaz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuestaaccesibilidad',
            name='q10_adaptaciones',
            field=models.CharField(choices=[('Siempre', 'Siempre'), ('A veces', 'A veces'), ('Nunca', 'Nunca')], max_length=20, verbose_name='10. Se utilizan adaptaciones curriculares o materiales accesibles (audiovisuales, digitales, adaptados).'),
        ),
        migrations.AlterField(
            model_name='encuestaaccesibilidad',
            name='q11_barreras',
            field=models.CharField(choices=[('Metodologias', 'Metodologías homogéneas'), ('Recursos', 'Falta de recursos didácticos accesibles'), ('Evaluaciones', 'Evaluaciones no adaptadas')], max_length=20, verbose_name='11. ¿Qué barreras pedagógicas identifica con mayor frecuencia?'),
        ),
        migrations.AlterField(
            model_name='encuestaaccesibilidad',
            name='q12_politicas',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No'), ('Desconozco', 'Desconozco')], max_length=20, verbose_name='12. La institución cuenta con políticas claras sobre inclusión y accesibilidad educativa.'),
        ),
        migrations.AlterField(
            model_name='encuestaaccesibilidad',
            name='q13_capacitacion_inst',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No'), ('Muy poca', 'Muy poca')], max_length=20, verbose_name='13. ¿Ha existido un proceso de capacitación por parte de la institución para que los docentes sepan cómo aplicar la accesibilidad y la inclusión en sus clases?'),
        ),
        migrations.AlterField(
            model_name='encuestaaccesibilidad',
            name='q14_conocimiento_bap',
            field=models.CharField(choices=[('Si', 'Si'), ('Parcialmente', 'Parcialmente'), ('Tal vez', 'Tal vez'), ('No', 'No')], max_length=20, verbose_name='14. ¿Existe un conocimiento institucional claro por parte de directivos y personal, sobre cómo identificar y eliminar las Barreras para el Aprendizaje y la Participación (BAP)?'),
        ),
        migrations.AlterField(
            model_name='encuestaaccesibilidad',
            name='q2_capacitacion',
            field=models.CharField(choices=[('Obstaculo', 'Ha sido un obstáculo total'), ('Dificultad', 'Me ha dificultado algunas cosas'), ('Perdido', 'A veces me siento perdido'), ('SinProblemas', 'He podido manejarlo sin problemas')], max_length=20, verbose_name='2. ¿De qué manera la ausencia de capacitación sobre el uso de la tecnología, ha afectado su desempeño en la plataforma institucional?'),
        ),
        migrations.AlterField(
            model_name='encuestaaccesibilidad',
            name='q3_compatibilidad',
            field=models.CharField(choices=[('Si', 'Si'), ('Lento', 'A veces falla o es lento'), ('Inestable', 'Funciona de forma inestable'), ('NoSoporta', 'Mi equipo no soporta la plataforma')], max_length=20, verbose_name='3. ¿Cuál es el nivel de compatibilidad (la capacidad de funcionamiento conjunto) entre sus dispositivos personales y los requisitos técnicos de la plataforma?'),
        ),
        migrations.AlterField(
            model_name='encuestaaccesibilidad',
            name='q4_soporte',
            field=models.CharField(choices=[('Si', 'Si'), ('No', 'No'), ('Tal vez', 'Tal vez')], max_length=20, verbose_name='4. ¿Ante una falla técnica o un bloqueo de acceso, ¿identifica usted los canales de soporte técnico (el servicio de asistencia para resolver problemas con la tecnología) disponibles?'),
        ),
        migrations.AlterField(
            model_name='encuestaaccesibilidad',
            name='q5_instalaciones',
            field=models.CharField(choices=[('Siempre', 'Siempre'), ('Casi siempre', 'Casi siempre'), ('A veces', 'A veces'), ('Nunca', 'Nunca')], max_length=20, verbose_name='5. ¿Considera que las instalaciones físicas de la institución (entrada, pasillos, aulas) permiten el desplazamiento autónomo y adecuado de personas con discapacidad física?'),
        ),
        migrations.AlterField(
            model_name='encuestaaccesibilidad',
            name='q6_apoyo',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No'), ('Parcialmente', 'Parcialmente')], max_length=20, verbose_name='6. ¿Cuenta la institución con elementos de apoyo como rampas, ascensores, baños accesibles y señalética inclusiva (letreros claros o en braille) en buen estado)'),
        ),
        migrations.AlterField(
            model_name='encuestaaccesibilidad',
            name='q7_recursos_tec',
            field=models.CharField(choices=[('Siempre', 'Siempre'), ('A veces', 'A veces'), ('Nunca', 'Nunca')], max_length=20, verbose_name='7. Los recursos tecnológicos (laboratorios, computadoras, plataformas digitales) son accesibles para todos los estudiantes.'),
        ),
        migrations.AlterField(
            model_name='encuestaaccesibilidad',
            name='q8_metodologias',
            field=models.CharField(choices=[('Siempre', 'Siempre'), ('A veces', 'A veces'), ('Rara vez', 'Rara vez'), ('Nunca', 'Nunca')], max_length=20, verbose_name='8. ¿Los docentes aplican metodologías inclusivas en el proceso de enseñanza-aprendizaje.?'),
        ),
        migrations.AlterField(
            model_name='encuestaaccesibilidad',
            name='q9_materiales',
            field=models.CharField(choices=[('Si', 'Sí'), ('No', 'No'), ('Parcialmente', 'Parcialmente')], max_length=20, verbose_name='9. ¿Considera que los contenidos y materiales del módulo están diseñados tomando en cuenta las diversas necesidades educativas (visuales, auditivas o cognitivas) de todos los estudiantes?'),
        ),
    ]
